import { Achievement } from "../types";

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "streak_3",
    title: "Getting Started",
    description: "3-day streak",
    icon: "🌱",
    requirement: 3,
    type: "streak",
  },
  {
    id: "streak_7",
    title: "One Week Strong",
    description: "7-day streak",
    icon: "🔥",
    requirement: 7,
    type: "streak",
  },
  {
    id: "streak_14",
    title: "Two Weeks Clean",
    description: "14-day streak",
    icon: "⭐",
    requirement: 14,
    type: "streak",
  },
  {
    id: "streak_30",
    title: "Monthly Master",
    description: "30-day streak",
    icon: "🏆",
    requirement: 30,
    type: "streak",
  },
  {
    id: "streak_60",
    title: "Dental Devotee",
    description: "60-day streak",
    icon: "💎",
    requirement: 60,
    type: "streak",
  },
  {
    id: "streak_100",
    title: "Century Club",
    description: "100-day streak",
    icon: "👑",
    requirement: 100,
    type: "streak",
  },
  {
    id: "streak_365",
    title: "Year of Smiles",
    description: "365-day streak",
    icon: "🎉",
    requirement: 365,
    type: "streak",
  },
  {
    id: "brush_50",
    title: "Brush Beginner",
    description: "50 brush sessions",
    icon: "🪥",
    requirement: 50,
    type: "total_brush",
  },
  {
    id: "brush_200",
    title: "Brush Pro",
    description: "200 brush sessions",
    icon: "✨",
    requirement: 200,
    type: "total_brush",
  },
  {
    id: "floss_30",
    title: "Floss Boss",
    description: "30 floss sessions",
    icon: "🦷",
    requirement: 30,
    type: "total_floss",
  },
  {
    id: "floss_100",
    title: "Floss Legend",
    description: "100 floss sessions",
    icon: "🌟",
    requirement: 100,
    type: "total_floss",
  },
  {
    id: "tongue_30",
    title: "Tongue Tamer",
    description: "30 tongue scrape sessions",
    icon: "👅",
    requirement: 30,
    type: "total_tongue_scrape",
  },
  {
    id: "mouthwash_30",
    title: "Fresh Breath Master",
    description: "30 mouthwash sessions",
    icon: "💧",
    requirement: 30,
    type: "total_mouthwash",
  },
  {
    id: "sessions_100",
    title: "Routine Regular",
    description: "100 complete sessions",
    icon: "🎯",
    requirement: 100,
    type: "total_sessions",
  },
];

export const DEFAULT_SETTINGS = {
  morningTime: "07:00",
  eveningTime: "21:00",
  notificationsEnabled: true,
  reminderIntervalMinutes: 15,
  useSameRoutine: true,
  morningRoutineId: null as string | null,
  eveningRoutineId: null as string | null,
  aiCoachingEnabled: false,
  dataVersion: 1,
};
